"""Phase 10: Controlled auto-release logic.

Auto-release flips a generated question from draft -> active automatically
when ALL of the following gates pass:

  1. Global config flag ``generation_auto_release_enabled`` is true.
  2. Runtime kill switch (``_auto_release_disabled``) is false.
  3. The question's batch ``release_policy == 'auto_release_on_accept'``.
  4. Consensus verdict is ``admin_review_ready``.
  5. ``high_disagreement_flag`` is false.
  6. ``official_overlap_status == 'none'``.
  7. The question's generation target matches at least one entry in
     ``generation_auto_release_allowed_targets``.
  8. The generator model has >= ``generation_auto_release_min_reviews``
     admin-reviewed questions AND an acceptance rate >=
     ``generation_auto_release_min_accept_rate``.

Every auto-release writes an immutable ``AutoReleaseAuditLog`` row.
The runtime kill switch can be toggled via the admin API without a restart.
"""

import json
import logging
import uuid
import inspect
from datetime import datetime, timezone
from typing import Any

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

logger = logging.getLogger(__name__)

# Runtime kill switch — can be flipped by the admin disable endpoint without restart.
# Takes precedence over config when True.
_auto_release_disabled: bool = False


def _allowed_targets_list(settings) -> list[dict]:
    """Parse ``generation_auto_release_allowed_targets`` JSON into a list of dicts."""
    raw = (settings.generation_auto_release_allowed_targets or "").strip()
    if not raw:
        return []
    try:
        parsed = json.loads(raw)
        if isinstance(parsed, list):
            return parsed
    except (json.JSONDecodeError, ValueError):
        logger.warning("generation_auto_release_allowed_targets is not valid JSON: %r", raw)
    return []


def _target_matches(question_annotation: dict | None, allowed: dict) -> bool:
    """Return True if the question's annotation satisfies one allowed-targets entry.

    Matching is additive: every key present in ``allowed`` must match the
    corresponding value in ``question_annotation``. Keys absent from
    ``allowed`` are wildcards.
    """
    if not allowed:
        return False
    ann = question_annotation or {}
    for key, expected in allowed.items():
        if ann.get(key) != expected:
            return False
    return True


async def _annotation_dict(question_id: uuid.UUID, db: AsyncSession) -> dict:
    """Load the latest annotation's key fields into a plain dict for target matching."""
    from app.models.db import QuestionAnnotation, Question
    result = await db.execute(
        select(QuestionAnnotation).join(
            Question, Question.latest_annotation_id == QuestionAnnotation.id
        ).where(Question.id == question_id)
    )
    ann = result.scalars().first()
    if ann is None:
        return {}
    ann_data = ann.annotation_jsonb if isinstance(ann.annotation_jsonb, dict) else {}
    reading_skill_family = (
        ann_data.get("reading_skill_family_key")
        or ann_data.get("skill_family_key")
    )
    domain = None
    if reading_skill_family or ann_data.get("reading_focus_key"):
        domain = "reading"
    elif ann_data.get("grammar_role_key") or ann_data.get("grammar_focus_key"):
        domain = "grammar"
    return {
        "domain": domain,
        "grammar_focus_key": ann_data.get("grammar_focus_key"),
        "grammar_role_key": ann_data.get("grammar_role_key"),
        "reading_focus_key": ann_data.get("reading_focus_key"),
        "reading_skill_family_key": reading_skill_family,
        "skill_family_key": reading_skill_family,
        "difficulty_overall": ann_data.get("difficulty_overall"),
    }


async def _generator_acceptance_stats(
    provider_name: str | None,
    model_name: str | None,
    db: AsyncSession,
) -> tuple[int, int, float | None]:
    """Return (accept_count, total_count, accept_rate) for a generator model.

    Counts questions generated by ``provider_name``/``model_name`` that have
    received an explicit admin decision (approved = active/rejected).
    """
    if not provider_name or not model_name:
        return 0, 0, None

    from app.models.db import QuestionJob, Question
    result = await db.execute(
        select(QuestionJob).where(
            QuestionJob.provider_name == provider_name,
            QuestionJob.model_name == model_name,
            QuestionJob.question_id.isnot(None),
        )
    )
    jobs = result.scalars().all()

    if not jobs:
        return 0, 0, None

    question_ids = [j.question_id for j in jobs]
    q_result = await db.execute(
        select(Question.id, Question.practice_status).where(
            Question.id.in_(question_ids),
            Question.practice_status.in_(["active", "rejected"]),
        )
    )
    decided = q_result.all()
    total = len(decided)
    accepted = sum(1 for row in decided if row.practice_status == "active")
    rate = accepted / total if total > 0 else None
    return accepted, total, rate


async def _write_auto_release_audit(
    *,
    question_id: uuid.UUID,
    consensus_verdict,
    db: AsyncSession,
    reasons: dict[str, Any],
    batch_id: uuid.UUID | None = None,
    release_policy: str | None = None,
    generator_provider: str | None = None,
    generator_model: str | None = None,
    accept_count: int = 0,
    total_count: int = 0,
    accept_rate: float | None = None,
) -> None:
    from app.models.db import AutoReleaseAuditLog

    audit_reasons = dict(reasons)
    audit_reasons.setdefault("result", "blocked")
    added = db.add(
        AutoReleaseAuditLog(
            id=uuid.uuid4(),
            question_id=question_id,
            generation_batch_id=batch_id,
            review_run_id=getattr(consensus_verdict, "review_run_id", None),
            consensus_verdict_id=getattr(consensus_verdict, "id", None),
            generator_provider_name=generator_provider,
            generator_model_name=generator_model,
            generator_accept_count=accept_count,
            generator_total_count=total_count,
            generator_accept_rate=accept_rate,
            release_policy=release_policy,
            reasons_jsonb=audit_reasons,
            released_at=datetime.now(timezone.utc),
        )
    )
    if inspect.isawaitable(added):
        await added
    await db.commit()


async def maybe_auto_release(
    question_id: uuid.UUID,
    consensus_verdict,  # ConsensusVerdict ORM instance
    db: AsyncSession,
    settings,
) -> bool:
    """Attempt auto-release for a question. Returns True if released.

    All gate checks are recorded in ``reasons_jsonb`` on the audit row
    regardless of outcome to simplify debugging.
    """
    from app.models.db import Question, GenerationBatch, QuestionJob

    reasons: dict[str, Any] = {}
    batch_id = getattr(consensus_verdict, "generation_batch_id", None)
    release_policy = None
    generator_provider = None
    generator_model = None
    accept_count = 0
    total_count = 0
    accept_rate = None

    question = await db.get(Question, question_id)
    if question is None:
        return False

    # Gate 1: global config flag
    reasons["config_enabled"] = settings.generation_auto_release_enabled
    if not settings.generation_auto_release_enabled:
        reasons["blocked_by"] = "config_disabled"
        await _write_auto_release_audit(
            question_id=question_id,
            consensus_verdict=consensus_verdict,
            db=db,
            reasons=reasons,
            batch_id=batch_id,
        )
        return False

    # Gate 2: runtime kill switch
    reasons["runtime_disabled"] = _auto_release_disabled
    if _auto_release_disabled:
        logger.info("Auto-release runtime kill switch is active; skipping q=%s", question_id)
        reasons["blocked_by"] = "runtime_disabled"
        await _write_auto_release_audit(
            question_id=question_id,
            consensus_verdict=consensus_verdict,
            db=db,
            reasons=reasons,
            batch_id=batch_id,
        )
        return False

    # Gate 4: consensus verdict must be admin_review_ready
    verdict_value = getattr(consensus_verdict, "consensus_verdict", None)
    reasons["consensus_verdict"] = verdict_value
    if verdict_value != "admin_review_ready":
        reasons["blocked_by"] = "consensus_verdict"
        await _write_auto_release_audit(
            question_id=question_id,
            consensus_verdict=consensus_verdict,
            db=db,
            reasons=reasons,
            batch_id=batch_id,
        )
        return False

    # Gate 5: no high disagreement
    high_flag = getattr(consensus_verdict, "high_disagreement_flag", False)
    reasons["high_disagreement_flag"] = high_flag
    if high_flag:
        reasons["blocked_by"] = "high_disagreement_flag"
        await _write_auto_release_audit(
            question_id=question_id,
            consensus_verdict=consensus_verdict,
            db=db,
            reasons=reasons,
            batch_id=batch_id,
        )
        return False

    # Gate 6: overlap clean
    overlap = getattr(question, "official_overlap_status", "none")
    reasons["official_overlap_status"] = overlap
    if overlap != "none":
        reasons["blocked_by"] = "overlap_not_clean"
        await _write_auto_release_audit(
            question_id=question_id,
            consensus_verdict=consensus_verdict,
            db=db,
            reasons=reasons,
            batch_id=batch_id,
        )
        return False

    # Gate 3: batch release_policy
    if batch_id:
        batch = await db.get(GenerationBatch, batch_id)
        release_policy = getattr(batch, "release_policy", None) if batch else None

    # Fall back to QuestionJob if batch link missing
    if release_policy is None:
        job_result = await db.execute(
            select(QuestionJob).where(QuestionJob.question_id == question_id)
            .order_by(QuestionJob.created_at.desc())
        )
        job = job_result.scalars().first()
        if job:
            batch_id = batch_id or job.generation_batch_id
            generator_provider = job.provider_name
            generator_model = job.model_name
            if batch_id and release_policy is None:
                batch = await db.get(GenerationBatch, batch_id)
                release_policy = getattr(batch, "release_policy", None) if batch else None
    else:
        job_result = await db.execute(
            select(QuestionJob).where(QuestionJob.question_id == question_id)
            .order_by(QuestionJob.created_at.desc())
        )
        job = job_result.scalars().first()
        if job:
            generator_provider = job.provider_name
            generator_model = job.model_name

    reasons["release_policy"] = release_policy
    if release_policy != "auto_release_on_accept":
        reasons["blocked_by"] = "release_policy_not_auto"
        await _write_auto_release_audit(
            question_id=question_id,
            consensus_verdict=consensus_verdict,
            db=db,
            reasons=reasons,
            batch_id=batch_id,
            release_policy=release_policy,
            generator_provider=generator_provider,
            generator_model=generator_model,
        )
        return False

    # Gate 7: allowed targets
    allowed_targets = _allowed_targets_list(settings)
    reasons["allowed_targets_count"] = len(allowed_targets)
    if not allowed_targets:
        reasons["blocked_by"] = "no_allowed_targets_configured"
        await _write_auto_release_audit(
            question_id=question_id,
            consensus_verdict=consensus_verdict,
            db=db,
            reasons=reasons,
            batch_id=batch_id,
            release_policy=release_policy,
            generator_provider=generator_provider,
            generator_model=generator_model,
        )
        return False

    ann_dict = await _annotation_dict(question_id, db)
    reasons["annotation_sample"] = {k: v for k, v in ann_dict.items() if v}
    target_match = any(_target_matches(ann_dict, t) for t in allowed_targets)
    reasons["target_matched"] = target_match
    if not target_match:
        reasons["blocked_by"] = "target_not_in_allowed_list"
        await _write_auto_release_audit(
            question_id=question_id,
            consensus_verdict=consensus_verdict,
            db=db,
            reasons=reasons,
            batch_id=batch_id,
            release_policy=release_policy,
            generator_provider=generator_provider,
            generator_model=generator_model,
        )
        return False

    # Gate 8: generator model acceptance history
    accept_count, total_count, accept_rate = await _generator_acceptance_stats(
        generator_provider, generator_model, db
    )
    reasons["generator_accept_count"] = accept_count
    reasons["generator_total_count"] = total_count
    reasons["generator_accept_rate"] = accept_rate

    min_reviews = settings.generation_auto_release_min_reviews
    min_rate = settings.generation_auto_release_min_accept_rate
    reasons["required_min_reviews"] = min_reviews
    reasons["required_min_accept_rate"] = min_rate

    if accept_count < min_reviews:
        reasons["blocked_by"] = "generator_insufficient_history"
        await _write_auto_release_audit(
            question_id=question_id,
            consensus_verdict=consensus_verdict,
            db=db,
            reasons=reasons,
            batch_id=batch_id,
            release_policy=release_policy,
            generator_provider=generator_provider,
            generator_model=generator_model,
            accept_count=accept_count,
            total_count=total_count,
            accept_rate=accept_rate,
        )
        return False
    if accept_rate is None or accept_rate < min_rate:
        reasons["blocked_by"] = "generator_accept_rate_too_low"
        await _write_auto_release_audit(
            question_id=question_id,
            consensus_verdict=consensus_verdict,
            db=db,
            reasons=reasons,
            batch_id=batch_id,
            release_policy=release_policy,
            generator_provider=generator_provider,
            generator_model=generator_model,
            accept_count=accept_count,
            total_count=total_count,
            accept_rate=accept_rate,
        )
        return False

    # All gates passed — activate
    reasons["result"] = "auto_released"
    question.practice_status = "active"
    await _write_auto_release_audit(
        question_id=question_id,
        consensus_verdict=consensus_verdict,
        db=db,
        reasons=reasons,
        batch_id=batch_id,
        release_policy=release_policy,
        generator_provider=generator_provider,
        generator_model=generator_model,
        accept_count=accept_count,
        total_count=total_count,
        accept_rate=accept_rate,
    )
    logger.info(
        "Auto-released question %s (generator=%s/%s, accept_rate=%.2f, count=%d)",
        question_id, generator_provider, generator_model,
        accept_rate or 0, accept_count,
    )
    return True
