#!/usr/bin/env python
"""TASK-07b / TASK-09 — calibrate DB annotation keys against CB ground truth.

Reads db_overlap_full.json (from match_bank_to_db.py). No DB access, no writes
outside this directory. Emits:

  db_overlap_full.md                          human-readable calibration report
  ../../vocabulary/mappings/cb_skill_map.json the old-key -> CB-skill map

The map is DERIVED from observed agreement, not hand-written: every rule carries
its sample size and purity, and anything below the bar is marked "review" rather
than guessed. It exists for questions that have NO CB match (generated,
unofficial, and the ~100 unmatched official rows). Matched rows never need it —
they take the CB label directly.

Usage: python3 calibration_report.py
"""
import collections
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
MAP_OUT = HERE.parent.parent / "vocabulary" / "mappings" / "cb_skill_map.json"
MIN_N, MIN_PURITY = 5, 0.95

GRAMMAR = ["Boundaries", "Form, Structure, and Sense", "Transitions", "Rhetorical Synthesis"]
KEY = {"Boundaries": "boundaries", "Form, Structure, and Sense": "form_structure_and_sense",
       "Transitions": "transitions", "Rhetorical Synthesis": "rhetorical_synthesis"}


def coe(k):  # CB has one Command of Evidence label; the DB splits it in two
    return "command_of_evidence" if k and k.startswith("command_of_evidence") else k


def rules(rows, keyfn):
    ct = collections.defaultdict(collections.Counter)
    for m in rows:
        ct[keyfn(m)][m["cb"]["skill"]] += 1
    out = []
    for k, c in ct.items():
        skill, top = c.most_common(1)[0]
        n = sum(c.values())
        purity = top / n
        out.append({"key": k, "skill_family_key": KEY[skill], "n": n,
                    "purity": round(purity, 3),
                    "status": "deterministic" if n >= MIN_N and purity >= MIN_PURITY else "review",
                    "counts": dict(c)})
    return sorted(out, key=lambda r: -r["n"])


def md_table(rs, label):
    lines = [f"| {label} | → skill | n | purity | status |", "|---|---|---|---|---|"]
    for r in rs:
        lines.append(f"| `{r['key']}` | {r['skill_family_key']} | {r['n']} | "
                     f"{r['purity']:.1%} | {r['status']} |")
    return "\n".join(lines)


def main():
    d = json.load(open(HERE / "db_overlap_full.json"))
    M = d["matches"]
    G = [m for m in M if m["cb"]["skill"] in GRAMMAR]
    R = [m for m in M if m["cb"]["skill"] not in GRAMMAR]

    by_stem = rules(G, lambda m: m["db"]["stem_type_key"])
    by_focus = rules(G, lambda m: f"{m['db']['gr']}/{m['db']['gf']}")
    by_role = rules(G, lambda m: m["db"]["gr"])

    agree = sum(1 for m in R if coe(m["db"]["sf"]) == coe(m["cb"]["skill_family_key"]))
    missing = sum(1 for m in R if not m["db"]["sf"])
    wrong = len(R) - agree - missing
    fam = sum(1 for m in M if m["db"]["qf"] == m["cb"]["question_family_key"])
    coe_rows = [m for m in R if (m["db"]["sf"] or "").startswith("command_of_evidence")
                and m["cb"]["skill"] == "Command of Evidence"]
    coe_ok = sum(1 for m in coe_rows if m["db"]["sf"] == m["cb"]["skill_family_key"])
    wic_as_grammar = sum(1 for m in R if m["cb"]["skill"] == "Words in Context" and m["db"]["gr"])
    per = collections.Counter(m["cb_question_id"] for m in M)
    copies = collections.Counter(per.values())
    admin = sum(1 for m in M if m["db"]["is_admin_edited"])

    MAP_OUT.parent.mkdir(parents=True, exist_ok=True)
    MAP_OUT.write_text(json.dumps({
        "_doc": "Derived by CB_QUESTION_BANK/09_2026/calibration_report.py from CB ground truth. "
                "Do not hand-edit; re-run to regenerate. Apply in order: stem_type_key, then "
                "role/focus, then role. Only 'deterministic' rules may be auto-applied.",
        "thresholds": {"min_n": MIN_N, "min_purity": MIN_PURITY},
        "calibration_rows": len(G),
        "by_stem_type_key": by_stem, "by_role_and_focus": by_focus, "by_role": by_role,
    }, indent=2) + "\n")

    det = lambda rs: sum(r["n"] for r in rs if r["status"] == "deterministic")
    report = f"""# CB bank × DB — overlap and calibration

Generated by `calibration_report.py` from `db_overlap_full.json`. Read-only analysis.

## Overlap

| | |
|---|---|
| CB bank questions | {d['bank_total']} |
| DB official rows | {d['db_official_total']} |
| **Bank questions found in DB** | **{d['bank_questions_matched']}** ({d['bank_questions_matched']/d['bank_total']:.1%} of the bank) |
| **DB rows those cover** | **{d['db_rows_matched']}** ({d['db_rows_matched']/d['db_official_total']:.1%} of official rows) |
| Needs human review | {d['needs_review']} |
| New to the DB | {len(d['unmatched_ids'])} |
| DB rows claimed by two different bank IDs | {len(d['db_id_collisions'])} |

Supersedes `db_overlap_check.md`, which covered only the 752-item Bank subset with a
strict stem matcher and reported 55.

### The DB stores the same question more than once

| DB copies per bank question | bank questions |
|---|---|
""" + "\n".join(f"| {k} | {v} |" for k, v in sorted(copies.items())) + f"""

The same CB question was ingested from several sources (2024 and 2025 releases of a
practice test, plus untitled re-imports). {d['db_rows_matched']} rows are
{d['bank_questions_matched']} distinct questions. Any per-question write must reach
**every** copy. Note `questions.cb_question_id` is `UNIQUE`, so it can label only one
copy per question — see ONTOLOGY_REFACTOR_PLAN.md §2.9.

{admin} matched rows are `is_admin_edited`.

## Existing annotations vs CB ground truth

| Check | Result |
|---|---|
| `question_family_key` (domain) agrees | {fam}/{len(M)} ({fam/len(M):.1%}) |
| Reading `skill_family_key` agrees | {agree}/{len(R)} ({agree/len(R):.1%}) |
| Reading `skill_family_key` missing | {missing} |
| Reading `skill_family_key` present but **wrong** | {wrong} |
| Words in Context rows annotated as a *grammar* question | {wic_as_grammar} |
| CoE textual/quantitative regex agrees with DB | {coe_ok}/{len(coe_rows)} |

## Grammar map, derived ({len(G)} calibration rows)

Rule is `deterministic` at n ≥ {MIN_N} and purity ≥ {MIN_PURITY:.0%}; otherwise `review`.

### 1. By `stem_type_key` — apply first

{md_table(by_stem, 'stem_type_key')}

### 2. By `grammar_role_key/grammar_focus_key`

{md_table(by_focus, 'role/focus')}

### 3. By `grammar_role_key` alone — fallback

{md_table(by_role, 'role')}

Rows covered by a deterministic rule: stem {det(by_stem)}, role/focus {det(by_focus)},
role {det(by_role)} of {len(G)}.
"""
    (HERE / "db_overlap_full.md").write_text(report)
    print(f"wrote db_overlap_full.md and {MAP_OUT.relative_to(HERE.parent.parent)}")
    print(f"domain agree {fam}/{len(M)} | reading skill agree {agree}/{len(R)} "
          f"missing {missing} wrong {wrong} | WIC-as-grammar {wic_as_grammar}")
    print(f"deterministic coverage: stem {det(by_stem)} | role/focus {det(by_focus)} "
          f"| role {det(by_role)} of {len(G)}")


if __name__ == "__main__":
    main()
