#!/usr/bin/env python3
"""Split the corrected DSAT rules monoliths into composable prompt modules.

Reads:
  rules_agent_dsat_grammar_ingestion_generation_v8.md
  rules_agent_dsat_reading_v3.md

Emits under rules/:
  shared/            modules needed by every call
  grammar/           cores, taxonomy, conditionals, examples, skills/<focus_key>.md
  reading/           cores, style fingerprint, skills/<skill_family>.md
  manifest.json      focus-key/skill-family -> ordered file load set
  split_report.json  line-coverage accounting (every source line assigned or
                     explicitly skipped; unassigned lines are an error)

Design rules:
  - Heading-regex driven; never fixed line numbers.
  - Appendix V (generated VOCAB blocks) and the Reference Quick-Index are
    intentionally excluded from prompt modules: Appendix V is validator-side
    (lockstep with backend/app/models/ontology.py via scripts/gen_vocab.py)
    and duplicates the prose taxonomy as a superset.
  - Idempotent: wipes and regenerates rules/ on each run.
"""
from __future__ import annotations

import json
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent
GRAMMAR_SRC = ROOT / "rules_agent_dsat_grammar_ingestion_generation_v8.md"
READING_SRC = ROOT / "rules_agent_dsat_reading_v3.md"
OUT = ROOT / "rules"

GENERATED_HEADER = (
    "<!-- generated by rules_refactor/split_rules.py — edit the source "
    "monolith and re-run; do not hand-edit -->\n\n"
)

# ---------------------------------------------------------------- utilities


class Doc:
    def __init__(self, path: Path):
        self.path = path
        self.lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
        self.assigned = [None] * len(self.lines)  # module name or "SKIP:<why>"

    def find(self, pattern: str, start: int = 0) -> int:
        rx = re.compile(pattern)
        for i in range(start, len(self.lines)):
            if rx.match(self.lines[i]):
                return i
        raise SystemExit(f"{self.path.name}: heading not found: {pattern!r}")

    def slice(self, start_pat: str, end_pat: str | None, module: str,
              start_from: int = 0) -> str:
        """Take [start_pat, end_pat) and mark the lines as assigned."""
        s = self.find(start_pat, start_from)
        e = self.find(end_pat, s + 1) if end_pat else len(self.lines)
        for i in range(s, e):
            if self.assigned[i] is None:
                self.assigned[i] = module
        return "".join(self.lines[s:e])

    def mark_skip(self, start_pat: str, end_pat: str | None, why: str) -> None:
        s = self.find(start_pat)
        e = self.find(end_pat, s + 1) if end_pat else len(self.lines)
        for i in range(s, e):
            if self.assigned[i] is None:
                self.assigned[i] = f"SKIP:{why}"

    def coverage(self) -> dict:
        unassigned = []
        run_start = None
        for i, a in enumerate(self.assigned):
            blank = self.lines[i].strip() == ""
            if a is None and not blank:
                if run_start is None:
                    run_start = i
            else:
                if run_start is not None:
                    unassigned.append([run_start + 1, i])  # 1-based inclusive-ish
                    run_start = None
        if run_start is not None:
            unassigned.append([run_start + 1, len(self.lines)])
        counts: dict[str, int] = {}
        for a in self.assigned:
            if a is not None:
                counts[a] = counts.get(a, 0) + 1
        return {
            "file": self.path.name,
            "total_lines": len(self.lines),
            "unassigned_nonblank_ranges": unassigned,
            "lines_per_module": dict(sorted(counts.items())),
        }


def write_module(rel: str, title: str, body: str) -> None:
    p = OUT / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(f"# {title}\n\n{GENERATED_HEADER}{body.rstrip()}\n",
                 encoding="utf-8")


def h3_blocks(text: str) -> list[tuple[str, str]]:
    """Split a section body into (### heading line, block text) pairs."""
    out: list[tuple[str, str]] = []
    cur_head, cur = None, []
    for line in text.splitlines(keepends=True):
        if line.startswith("### "):
            if cur_head is not None:
                out.append((cur_head, "".join(cur)))
            cur_head, cur = line.rstrip("\n"), [line]
        elif cur_head is not None:
            cur.append(line)
    if cur_head is not None:
        out.append((cur_head, "".join(cur)))
    return out


def key_of(heading: str) -> str | None:
    m = re.search(r"`([a-z_]+)`", heading)
    return m.group(1) if m else None


# ---------------------------------------------------------------- grammar

GRAMMAR_ROLE_BY_FOCUS = {
    # D.8.1 (with absolute_phrase fix applied)
    "sentence_fragment": "sentence_boundary", "comma_splice": "sentence_boundary",
    "run_on_sentence": "sentence_boundary", "sentence_boundary": "sentence_boundary",
    "subject_verb_agreement": "agreement", "pronoun_antecedent_agreement": "agreement",
    "noun_countability": "agreement", "determiners_articles": "agreement",
    "affirmative_agreement": "agreement",
    "pronoun_case": "pronoun", "pronoun_clarity": "pronoun",
    "verb_tense_consistency": "verb_form", "verb_form": "verb_form",
    "voice_active_passive": "verb_form", "negation": "verb_form",
    "modifier_placement": "modifier", "absolute_phrase": "modifier",
    "comparative_structures": "modifier", "illogical_comparison": "modifier",
    "adjective_adverb_distinction": "modifier", "logical_predication": "modifier",
    "relative_pronouns": "modifier",
    "punctuation_comma": "punctuation", "colon_dash_use": "punctuation",
    "semicolon_use": "punctuation", "conjunctive_adverb_usage": "punctuation",
    "apostrophe_use": "punctuation", "possessive_contraction": "punctuation",
    "appositive_punctuation": "punctuation", "hyphen_usage": "punctuation",
    "quotation_punctuation": "punctuation",
    "unnecessary_internal_punctuation": "punctuation",
    "end_punctuation_question_statement": "punctuation",
    "parallel_structure": "parallel_structure",
    "elliptical_constructions": "parallel_structure",
    "conjunction_usage": "parallel_structure",
    "redundancy_concision": "expression_of_ideas",
    "precision_word_choice": "expression_of_ideas",
    "register_style_consistency": "expression_of_ideas",
    "logical_relationships": "expression_of_ideas",
    "emphasis_meaning_shifts": "expression_of_ideas",
    "data_interpretation_claims": "expression_of_ideas",
    "transition_logic": "expression_of_ideas",
    "commonly_confused_words": "expression_of_ideas",
    "preposition_idiom": "expression_of_ideas",
}

# B.3 headings that are NOT standalone focus keys
GRAMMAR_B3_MERGE = {  # pseudo-heading key -> parent skill file
    "finite_verb_in_relative_clause": "verb_form",
    "finite_verb_in_main_clause": "verb_form",
    "modal_plus_plain_form": "verb_form",
    "singular_event_reference": "pronoun_antecedent_agreement",
}
CROSS_KEY_NOTE = "Matching Delimiter Rule"
NOTES_SYNTH_STEM = "choose_best_notes_synthesis"

PUNCTUATION_DELIMITER_KEYS = [
    "punctuation_comma", "colon_dash_use", "semicolon_use",
    "appositive_punctuation", "unnecessary_internal_punctuation",
]


def split_grammar(doc: Doc) -> dict:
    # ---- shared / cores
    shared = doc.slice(r"^## Purpose", r"^# PART B", "shared/00_mode_and_schemas.md")
    write_module("shared/00_mode_and_schemas.md",
                 "DSAT Rules — Purpose, Mode Routing, Output Schemas (grammar v8 Part A)",
                 shared)

    gen_core_parts = [
        doc.slice(r"^# PART B", r"^## B\.3\.0 ", "grammar/generation_core.md"),
        doc.slice(r"^## B\.3\.0 ", r"^## B\.3 Passage", "grammar/generation_core.md"),
        doc.slice(r"^## B\.7 ", r"^## B\.12 ", "grammar/generation_core.md"),
        doc.slice(r"^## B\.13 ", r"^# PART C", "grammar/generation_core.md"),
        doc.slice(r"^# PART E", r"^#+ Reference Quick-Index", "grammar/generation_core.md"),
    ]
    write_module("grammar/generation_core.md",
                 "Grammar Generation Core (B.1–B.2, B.3.0, B.7–B.11, B.13–B.15, Part E)",
                 "\n".join(gen_core_parts))

    ann_core = (
        doc.slice(r"^# PART C", r"^# PART D", "grammar/annotation_core.md")
        + "\n"
        + doc.slice(r"^## D\.4 ", r"^## D\.5 ", "grammar/annotation_core.md")
    )
    write_module("grammar/annotation_core.md",
                 "Grammar Annotation/Ingestion Core (Part C + D.4 decision tree)",
                 ann_core)

    taxonomy = "\n".join([
        doc.slice(r"^# PART D", r"^## D\.4 ", "grammar/taxonomy.md"),
        doc.slice(r"^## D\.5 ", r"^## D\.10 ", "grammar/taxonomy.md"),
    ])
    write_module("grammar/taxonomy.md",
                 "Grammar Taxonomy Reference (D.1–D.3, D.5–D.9)", taxonomy)

    write_module("grammar/future_anatomy.md",
                 "Sentence Anatomy Keys — future Pass-3 span annotation (D.10)",
                 doc.slice(r"^## D\.10 ", r"^#+ Reference Quick-Index",
                           "grammar/future_anatomy.md"))

    write_module("grammar/conditional/transitions.md",
                 "Transition Subtype Vocabulary (B.5) — load only for transition_logic",
                 doc.slice(r"^## B\.5 ", r"^## B\.6 ", "grammar/conditional/transitions.md"))

    notes_body = doc.slice(r"^## B\.6 ", r"^## B\.7 ", "grammar/conditional/notes_synthesis.md")

    # ---- B.12 examples
    b12 = doc.slice(r"^## B\.12 ", r"^## B\.13 ", "grammar/examples")
    for head, block in h3_blocks(b12):
        k = key_of(head)
        if k:
            write_module(f"grammar/examples/{k}.md",
                         f"Worked generation example — {k} (B.12)", block)

    # ---- B.3 per-skill blocks
    b3 = doc.slice(r"^## B\.3 Passage", r"^## B\.4 ", "grammar/skills")
    b4 = doc.slice(r"^## B\.4 ", r"^## B\.5 ", "grammar/skills")

    skills: dict[str, list[str]] = {}
    cross_key_note_text = None
    notes_synth_b3 = None
    for head, block in h3_blocks(b3):
        if CROSS_KEY_NOTE in head:
            cross_key_note_text = block
            continue
        k = key_of(head)
        if k is None:
            raise SystemExit(f"B.3 heading without key: {head!r}")
        if k == NOTES_SYNTH_STEM:
            notes_synth_b3 = block
            continue
        target = GRAMMAR_B3_MERGE.get(k, k)
        skills.setdefault(target, []).append(block)

    for head, block in h3_blocks(b4):
        k = key_of(head)
        if k is None:
            raise SystemExit(f"B.4 heading without key: {head!r}")
        skills.setdefault(k, []).append(
            "## Distractor table (B.4)\n\n" + block.split("\n", 1)[1].lstrip("\n")
        )

    unknown = set(skills) - set(GRAMMAR_ROLE_BY_FOCUS)
    if unknown:
        raise SystemExit(f"B.3/B.4 keys not in role map: {sorted(unknown)}")
    missing_b3 = set(GRAMMAR_ROLE_BY_FOCUS) - set(skills)
    if missing_b3:
        raise SystemExit(f"focus keys with no B.3/B.4 content: {sorted(missing_b3)}")

    for k, parts in skills.items():
        role = GRAMMAR_ROLE_BY_FOCUS[k]
        meta = (f"`grammar_focus_key: {k}` — `grammar_role_key: {role}`\n\n"
                "Load with: shared/00_mode_and_schemas.md, grammar/generation_core.md "
                "(or annotation_core.md), grammar/taxonomy.md, plus conditionals "
                "listed in manifest.json.\n")
        body = meta + "\n" + "\n".join(parts)
        if k in PUNCTUATION_DELIMITER_KEYS and cross_key_note_text:
            body += "\n\n" + cross_key_note_text
        write_module(f"grammar/skills/{k}.md",
                     f"Grammar skill module — {k}", body)

    write_module("grammar/conditional/notes_synthesis.md",
                 "Notes Synthesis Metadata (B.6) — load only for choose_best_notes_synthesis",
                 (notes_synth_b3 or "") + "\n" + notes_body)

    # ---- skips
    doc.mark_skip(r"^#+ Reference Quick-Index", r"^## Appendix V",
                  "quick-index (human navigation aid)")
    doc.mark_skip(r"^## Appendix V", None,
                  "generated VOCAB appendix (validator-side; source = vocabulary/master.json)")

    # ---- manifest entries
    manifest: dict = {"skills": {}}
    for k in sorted(skills):
        cond = []
        if k == "transition_logic":
            cond.append("grammar/conditional/transitions.md")
        entry = {
            "role": GRAMMAR_ROLE_BY_FOCUS[k],
            "generate": ["shared/00_mode_and_schemas.md",
                         "grammar/generation_core.md",
                         "grammar/taxonomy.md",
                         f"grammar/skills/{k}.md", *cond],
            "annotate": ["shared/00_mode_and_schemas.md",
                         "grammar/annotation_core.md",
                         "grammar/taxonomy.md",
                         f"grammar/skills/{k}.md", *cond],
        }
        example = OUT / f"grammar/examples/{k}.md"
        if example.exists():
            entry["generate"].append(f"grammar/examples/{k}.md")
        manifest["skills"][k] = entry
    manifest["stem_type_overrides"] = {
        "choose_best_notes_synthesis": {
            "generate": ["shared/00_mode_and_schemas.md",
                         "grammar/generation_core.md",
                         "grammar/taxonomy.md",
                         "grammar/conditional/notes_synthesis.md"],
            "annotate": ["shared/00_mode_and_schemas.md",
                         "grammar/annotation_core.md",
                         "grammar/taxonomy.md",
                         "grammar/conditional/notes_synthesis.md"],
        }
    }
    manifest["do_not_generate"] = ["affirmative_agreement", "negation"]
    return manifest


# ---------------------------------------------------------------- reading

READING_FAMILY_SECTIONS = {
    # family -> (§7.x, §13.x, §19.x or None)
    "command_of_evidence_textual": ("7.1", "13.1", "19.3"),
    "command_of_evidence_quantitative": ("7.2", "13.2", "19.2"),
    "central_ideas_and_details": ("7.3", "13.3", None),
    "inferences": ("7.4", "13.4", "19.4"),
    "words_in_context": ("7.5", "13.5", "19.1"),
    "text_structure_and_purpose": ("7.6", "13.6", "19.5"),
    "cross_text_connections": ("7.7", "13.7", "19.6"),
}

READING_FOCUS_BY_FAMILY = {
    "command_of_evidence_textual": [
        "evidence_supports_claim", "evidence_weakens_claim",
        "evidence_illustrates_claim", "evidence_explains_claim",
        "evidence_qualifies_claim"],
    "command_of_evidence_quantitative": [
        "data_supports_claim", "data_weakens_claim", "data_completes_example",
        "data_comparison", "data_trend"],
    "central_ideas_and_details": [
        "central_idea", "main_purpose", "passage_summary", "supporting_detail",
        "character_or_author_detail"],
    "inferences": [
        "causal_inference", "motivational_inference", "implication_inference",
        "predictive_inference", "cross_text_inference"],
    "words_in_context": [
        "contextual_meaning", "connotation_fit", "precision_fit", "register_fit",
        "underlined_word_meaning", "polarity_fit", "figurative_language_meaning"],
    "text_structure_and_purpose": [
        "overall_purpose", "sentence_function", "structural_pattern",
        "author_stance"],
    "cross_text_connections": [
        "text2_response_to_text1", "both_texts_agree", "texts_disagree",
        "text2_qualifies_text1", "text2_contradicts_text1",
        "methodological_critique", "expectation_violation"],
}


def subsection(doc: Doc, num: str, module: str) -> str:
    """Slice '### <num> ' up to the next ### or ## heading."""
    s = doc.find(rf"^### {re.escape(num)}\b")
    e = s + 1
    while e < len(doc.lines) and not re.match(r"^##+ ", doc.lines[e]):
        e += 1
    for i in range(s, e):
        if doc.assigned[i] is None:
            doc.assigned[i] = module
    return "".join(doc.lines[s:e])


def split_reading(doc: Doc) -> dict:
    core = "\n".join([
        doc.slice(r"^## Purpose", r"^## 7\. ", "reading/core_taxonomy.md"),
        doc.slice(r"^## 8\. ", r"^## 13\. ", "reading/core_taxonomy.md"),
        doc.slice(r"^## 17\. ", r"^## 19\. ", "reading/core_taxonomy.md"),
        doc.slice(r"^## 20\. ", r"^## 21\. ", "reading/core_taxonomy.md"),
    ])
    write_module("reading/core_taxonomy.md",
                 "Reading Core Taxonomy (Purpose, §1–§6, §8–§12, §17–§18, §20)", core)

    write_module("reading/annotation_core.md",
                 "Reading Annotation Core (§21 validator checklist; per-skill "
                 "annotation rules live in skills/)",
                 doc.slice(r"^## 21\. ", r"^## 22\. ", "reading/annotation_core.md"))

    # §16.9 table rows get distributed per family; the rest of §16 + §14 + §15 + §23 = generation core
    sec169 = subsection(doc, "16.9", "reading/skills(16.9)")
    gen_core = "\n".join([
        doc.slice(r"^## 14\. ", r"^## 16\. ", "reading/generation_core.md"),
        doc.slice(r"^## 16\. ", r"^### 16\.9\b", "reading/generation_core.md"),
        doc.slice(r"^## 23\. ", r"^## Appendix V", "reading/generation_core.md"),
    ])
    write_module("reading/generation_core.md",
                 "Reading Generation Core (§14–§16.8, §23)", gen_core)

    write_module("reading/style_fingerprint.md",
                 "Reading Passage Style Fingerprint (§22) — generation only",
                 doc.slice(r"^## 22\. ", r"^## 23\. ", "reading/style_fingerprint.md"))

    # §16.9 rows: header + rows filtered per family
    lines169 = [l for l in sec169.splitlines() if l.strip()]
    table_head = [l for l in lines169 if l.startswith("|")][:2]
    rows = [l for l in lines169 if l.startswith("|")][2:]
    preamble = "\n".join(l for l in lines169 if not l.startswith("|") and not l.startswith("###"))

    # §7 intro (before 7.1) belongs to every fragment's context; slice per family
    manifest: dict = {"skills": {}}
    doc.slice(r"^## 7\. ", r"^### 7\.1\b", "reading/skills(§7 intro)")
    sec7_intro = "".join(doc.lines[doc.find(r"^## 7\. "):doc.find(r"^### 7\.1\b")])
    doc.slice(r"^## 13\. ", r"^### 13\.1\b", "reading/skills(§13 intro)")
    doc.slice(r"^## 19\. ", r"^### 19\.1\b", "reading/skills(§19 intro)")
    doc.slice(r"^### 19\.7\b", r"^## 20\. ", "reading/core_taxonomy.md(19.7 summary)")

    for family, (s7, s13, s19) in READING_FAMILY_SECTIONS.items():
        parts = [sec7_intro, subsection(doc, s7, f"reading/skills/{family}.md"),
                 subsection(doc, s13, f"reading/skills/{family}.md")]
        if s19:
            parts.append(subsection(doc, s19, f"reading/skills/{family}.md"))
        fam_focus = set(READING_FOCUS_BY_FAMILY[family])
        fam_rows = [r for r in rows
                    if (m := re.search(r"`([a-z0-9_]+)`", r)) and m.group(1) in fam_focus]
        if fam_rows:
            parts.append("### Per-focus generation and distractor recipes (§16.9)\n\n"
                         + preamble + "\n\n" + "\n".join(table_head + fam_rows))
        write_module(f"reading/skills/{family}.md",
                     f"Reading skill module — {family}", "\n\n".join(parts))
        manifest["skills"][family] = {
            "focus_keys": READING_FOCUS_BY_FAMILY[family],
            "generate": ["shared/00_mode_and_schemas.md",
                         "reading/core_taxonomy.md",
                         "reading/generation_core.md",
                         "reading/style_fingerprint.md",
                         f"reading/skills/{family}.md"],
            "annotate": ["shared/00_mode_and_schemas.md",
                         "reading/core_taxonomy.md",
                         "reading/annotation_core.md",
                         f"reading/skills/{family}.md"],
        }

    doc.mark_skip(r"^## Appendix V", None,
                  "generated VOCAB appendix (validator-side; source = vocabulary/master.json)")
    # version footer travels with generation core's tail slice already? No — it
    # sits between §23 end and Appendix V, so the §23 slice captured it.
    return manifest


# ---------------------------------------------------------------- main

def main() -> None:
    if OUT.exists():
        shutil.rmtree(OUT)
    gdoc, rdoc = Doc(GRAMMAR_SRC), Doc(READING_SRC)
    for d in (gdoc, rdoc):
        d.assigned[0] = "SKIP:source title line"
    manifest = {
        "version": "rules-refactor v1 (grammar v8.2-refactor + reading v3.1-refactor)",
        "grammar": split_grammar(gdoc),
        "reading": split_reading(rdoc),
    }
    (OUT / "manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    report = {"grammar": gdoc.coverage(), "reading": rdoc.coverage()}
    (OUT / "split_report.json").write_text(
        json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    for name, cov in report.items():
        gaps = cov["unassigned_nonblank_ranges"]
        status = "OK" if not gaps else f"UNASSIGNED RANGES: {gaps}"
        print(f"{name}: {cov['total_lines']} lines — {status}")
    n_files = sum(1 for _ in OUT.rglob("*.md"))
    print(f"emitted {n_files} modules under {OUT}")


if __name__ == "__main__":
    main()
